empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'app_dpto'

urlpatterns = [
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name='nuevo_departamento'
    ),
    path(
        'departamento_lista',
        views.DepartamentoListView.as_view(),
        name='departamento_list'
    ),
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views
# usando reverse_lazy debemos especificar la etiqueta NAME de una URL

# Usando reverse_lazy definimos la variable para todo el conjunto de URL
# La convencion recomienda usar el nombre del modelo seguido de _app
app_name = "persona_app"
urlpatterns = [
     path(
          'lista-todo-empleados/', 
          views.ListAllEmpleados.as_view(),
          name='empleados_all'
     ),
     path(
          'lista-by-area/<corto>', 
          views.ListByAreaEmpleado.as_view(),
          name='empleados_area'
     ),
     path(
          'lista-empleados-admin',
          views.ListaEmpleadosAdmin.as_view(),
          name='empleados_admin'
     ),
     path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
     path('listar-habilidades/', views.ListHabilidadesEmpleado.as_view()),
     path('listar-por-trabajo/', views.ListEmpleadoByTrabajo.as_view()),
     path(
          'ver-empleado/<pk>/', 
          views.DetalleEmpleado.as_view(),
          name='empleado_detail'
     ),
     path(
          'add-empleado/',
          views.EmpleadoCreateView.as_view(),
          name='empleado_agrega'
     ),
     path(
          'success/', 
          views.SuccessView.as_view(), 
          name='correcto'
     ),
     path(
          'update-empleado/<pk>/',
          views.EmpleadoUpdateView.as_view(),
          name='modificar_empleado'
     ),
     path(
          'delete-empleado/<pk>/',
          views.EmpleadoDeleteView.as_view(),
          name='eliminar_empleado'
     ),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from applications.home.views import IndexView
# Importar configuracion de django
from django.conf import settings
# importar paquete que ayuda a generar URLs estaticas
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('home/', IndexView.as_view()),
    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Ver archivos dentro de la carpeta MEDIA

empleado/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
<!--           <ul class="menu vertical">
            <li><a href="#">One</a></li>
            <li><a href="#">Two</a></li>
            <li><a href="#">Three</a></li>
          </ul> -->
        </li>
        <li><a href="{% url 'app_dpto:departamento_list' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <li><a href="{% url 'persona_app:empleado_agrega' %}" class="button primary">Registrar Nuevo</a></li>
      </ul>
    </div>
  </div>