empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views
# usando reverse_lazy debemos especificar la etiqueta NAME de una URL

# Usando reverse_lazy definimos la variable para todo el conjunto de URL
# La convencion recomienda usar el nombre del modelo seguido de _app
app_name = "persona_app"
urlpatterns = [
     path(
          'lista-todo-empleados/', 
          views.ListAllEmpleados.as_view(),
          name='empleados_all'
     ),
     path(
          'lista-by-area/<corto>', 
          views.ListByAreaEmpleado.as_view(),
          name='empleados_area'
     ),
     path(
          'lista-empleados-admin',
          views.ListaEmpleadosAdmin.as_view(),
          name='empleados_admin'
     ),
     path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
     path('listar-habilidades/', views.ListHabilidadesEmpleado.as_view()),
     path('listar-por-trabajo/', views.ListEmpleadoByTrabajo.as_view()),
     path(
          'ver-empleado/<pk>/', 
          views.DetalleEmpleado.as_view(),
          name='empleado_detail'
     ),
     path(
          'add-empleado/',
          views.EmpleadoCreateView.as_view(),
          name='empleado_agrega'
     ),
     path(
          'success/', 
          views.SuccessView.as_view(), 
          name='correcto'
     ),
     path(
          'update-empleado/<pk>/',
          views.EmpleadoUpdateView.as_view(),
          name='modificar_empleado'
     ),
     path(
          'delete-empleado/<pk>/',
          views.EmpleadoDeleteView.as_view(),
          name='eliminar_empleado'
     ),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from applications.home.views import IndexView
# Importar configuracion de django
from django.conf import settings
# importar paquete que ayuda a generar URLs estaticas
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('home/', IndexView.as_view()),
    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Ver archivos dentro de la carpeta MEDIA

empleado/applications/persona/models.py
from unittest.util import _MIN_COMMON_LEN
from django.db import models
from ckeditor.fields import RichTextField
from django.forms import ImageField

from applications.departamento.models import Departamento

# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades del empleado'

    def __str__(self):
        return str(self.id) + ' - ' + self.habilidad

class Empleado(models.Model):
    """ Modelo para tabla empleado """
    # Lista de opciones para JOB
    JOB_CHOICES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro'),
        ('4', 'Ingeniero'),
        ('5', 'Abogado'),
        ('6', 'Técnico'),
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField(
        'Nombres completos',
        max_length=120,
        blank=True
    )
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    # Personalizar el modelo en el admin de django
    class Meta:
        verbose_name = 'Trabajadores de la empresa'
        verbose_name_plural = 'Colaboradores'
        ordering = ['last_name', '-first_name']
        # VERIFICAR que no haya valores duplicados en estos campos
        unique_together = ('last_name', 'first_name')


    def __str__(self):
        return str(self.id) + ' - ' + self.first_name + ' ' + self.last_name

empleado/applications/persona/views.py
from django.shortcuts import render
# El paquete reverse_lazy es la mejor práctica para redirigir a paginas
# Se necesitara colocar nombre a los URL
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Empleado

# 1. Listar todos los empleados de la empresa.
class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    # Indicar tamaño de bloques paginacion
    paginate_by = 10
    # Ordenando los resultados
    ordering = ['first_name', 'last_name']
    model = Empleado
    context_object_name = 'lista'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')

        lista = Empleado.objects.filter(
            # icontains, busca una cadena DENTRO de otra, incluso mayusculas y minusculas
            #full_name__icontains = palabra_clave
            first_name__icontains = palabra_clave
        )
        return lista
        
class ListaEmpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    # Indicar tamaño de bloques paginacion
    paginate_by = 10
    # Ordenando los resultados
    ordering = ['last_name', 'first_name']
    model = Empleado
    context_object_name = 'empleadoslista'


# 2. Listar todos los empleados que pertenecen a un area de la empresa.
class ListByAreaEmpleado(ListView):
    template_name = 'persona/list_by_area.html'
    # La PEOR forma de hacer filtrado
    #queryset = Empleado.objects.filter(
        #departamento__shor_name = 'OIS'
        #departamento__name = 'Economia y Finanzas'
    #)
    context_object_name = 'empleados'
    # Mejor forma de hacer filtrado
    def get_queryset(self):
        # Recoger un argumento que envian por la URL
        area = self.kwargs['corto']
        lista = Empleado.objects.filter(
            #departamento__shor_name = 'OIS'
            #departamento__shor_name = 'OEF'
            departamento__shor_name=area
        )
        return lista

# 3. Listar empleados por trabajo.
class ListEmpleadoByTrabajo(ListView):
    template_name = 'persona/empleado_by_trabajo.html'
    context_object_name = 'trabajo'
    
    def get_queryset(self):
        clave_trabajo = self.request.GET.get("kwork", '')
        trabajo = Empleado.objects.filter(
            job=clave_trabajo
        )
        #print(trabajo)
        return trabajo

# 4. Listar los empleados por palabra clave.
class ListEmpleadosByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        print('**************************')
        # self
        # request -> solicitudes enviadas al servidor, es objeto completo. 
        # GET -> (metodo) 
        # get -> (submetodo) recupera al identificador (id) "kword". Se agrega coma y '' porque es una TUPLA.
        palabra_clave = self.request.GET.get("kword", '')
        #print('=============\n', palabra_clave)
        # FILTRAMOS los datos, de un CONJUNTO DE REGISTROS (varios)
        lista = Empleado.objects.filter(
            first_name = palabra_clave
        )
        #print('LISTA RESULTADO:\n', lista)
        return lista

# 5. Listar habilidades de un empleado.
class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        # Filtramos los datos de UN SOLO empleado (recupera un solo registro)
        empleado = Empleado.objects.get(id=56)
        #print(empleado.habilidades.all())
        return empleado.habilidades.all()

# DetailView es muy similar al ListView
# Es para ver los detalles (campos) de un registro
class DetalleEmpleado(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    # Intervenir un metodo, redifinirlo
    def get_context_data(self, **kwargs):
        context = super(DetalleEmpleado, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context

# Plantilla que servira para redirigir luego que se agrego un registro
class SuccessView(TemplateView):
    template_name = "persona/success.html"

class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    # OBLIGATORIO para el CreateView
    # para cargar campos determinados
    fields = ['first_name', 'last_name', 'job', 'departamento', 'habilidades', 'image', ]
    # Agrega TODOS LOS CAMPOS del Modelo
    # fields = ('__all__')
    # CREATEVIEW necesita el success_url para redireccionar cuando se completo la ejecucion del formulario
    #success_url = '/success/' 
    success_url = reverse_lazy('persona_app:empleados_all') # Usamos etiquetas reverse_Lazy con nombre
    # '.' para que se cargue en la misma pagina.
    # No es bueno hacer esta redireccion, se debe hacer de la siguiente manera:

    # Este metodo es para interceptar el registro que se envía a la BD del modelo
    def form_valid(self, form):
        # declaramos la variable empleado y recuperamos la instancia vinculada a la BD
        empleado = form.save()
        # form.save(), a este momento el registro ya esta guardado en la BD, ahora lo podemos utilizar, y como muestra es que lo imprimimos
        # print(empleado)
        # A la instancia empleado que habiamos recuperado, estamos actualizado su valor full_name, solo en la variable
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        # la variable empleado -al ser una instancia del modelo empleado- se invoca al metodo SAVE() para que sus valores se actualicen, de esta manera el full_name se actualizara con el último valor creado
        empleado.save()
        # Se esta trabajando dentro de la vista generica
        return super(EmpleadoCreateView, self).form_valid(form)
    
class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    # Para modificar - actualizar TODOS los campos
    #fields = ('__all__')
    # Para Actualizar-Modificar determinados campos
    fields = ['first_name', 'last_name', 'job', 'departamento', 'habilidades', 'image', ]
    # Luego de guardarse correctamente se direcciona a la URL CORRECTO
    #success_url = reverse_lazy('persona_app:correcto')
    # Luego de guardarse correctamente se direcciona a la pagina empleados_admin
    success_url = reverse_lazy('persona_app:empleados_admin')

    # Para interceptar los valores antes que se guarden
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('********* METODO POST ********')
        print('==============================')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        print('********** FORM VALID ********')
        print('******************************')
        empleados = form.save()
        empleados.full_name = empleados.first_name + ' ' + empleados.last_name
        empleados.save()
        return super(EmpleadoUpdateView, self).form_valid(form)

class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    # Luego de guardarse correctamente se direcciona a la URL CORRECTO
    #success_url = reverse_lazy('persona_app:correcto')
    # Luego de guardarse correctamente se direcciona a la pagina empleados_admin
    success_url = reverse_lazy('persona_app:empleados_admin')

    

empleado/templates/persona/add.html
{% extends 'base.html' %}

{% block titulo %}
    Agregar Nuevo Empleado
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>
        <div class="cell">
            <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}

                <div class="medium-6 cell">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Trabajo:
                        {{ form.job }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Area:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <label>Habilidades:
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <label>Foto:
                        {{form.image}}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button clasS="button success" type="submit">Guardar</button>
                </div>
            </form>
        </div>

    </div>
</div>

{% endblock content %}

empleado/templates/persona/by_kword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Por palabras filtradas</title>
</head>
<body>
    <h1>Buscar empleados por palabra clave</h1>

    <form method="GET">{% csrf_token %}
        <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aqui">
        <button type="submit">Buscar</button>
    </form>

    <h3>Lista de resultados</h3>
    <ul>
        {% for e in empleados %}
        <li>{{e}}</li>
        {% endfor %}
    </ul>
    
</body>
</html>

empleado/templates/persona/delete.html
{% extends 'base.html' %}


{% block titulo %}
Eliminar registro Empleado
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{ object.full_name }} </h1>
        <div class="cell">
            <form class="cell" method="POST">{% csrf_token %}

                <div class="callout alert">
                    <h5>¿Desea eliminar este empleado?</h5>
                    <p>Recuerde que .... .</p>
                    
                    <button type="submit" class="button alert">Confirmar</button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock content %}

empleado/templates/persona/detail_empleado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail View</title>
</head>
<body>
<h1>Detail View - Detalle del Empleado {{ titulo }} </h1>
{{ empleado }}
<h2>Detalles:</h2>
<p>{{ empleado.first_name }}</p>
<p>{{ empleado.last_name }}</p>
<p>{{ empleado.departamento }}</p>
<p>{{ empleado.habilidades }}</p>
<p>{{ empleado.job }}</p>

</body>
</html>

empleado/templates/persona/empleado_by_trabajo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Empleados por trabajo</title>
</head>
<body>
<h3>Empleados por trabajo</h3>
<h2>Escriba el numero para filtrar según trabajo:</h2>
<ul>
    <li>0 => Contador</li>
    <li>1 => Administrador</li>
    <li>2 => Economista</li>
    <li>3 => Otro</li>
    <li>4 => Ingeniero</li>
    <li>5 => Abogado</li>
    <li>6 => Técnico</li>
</ul>

<form method="GET">{% csrf_token %}
    <input type="text" id="kwork" name="kwork" placeholder="Escribe numero de 0 a 6">
    <button type="submit">Buscar</button>
</form>
<ul>
    {% for e in trabajo %}
    <li>{{ e }}</li>
    {% endfor %}
</ul>
</body>
</html>

empleado/templates/persona/habilidades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Habilidades</title>
</head>
<body>
    <h1>Habilidades del empleado</h1>
    <ul>
        {% for e in habilidades %}
        <li>{{ e }}</li>
        {% endfor %}
    </ul>
</body>
</html>

empleado/templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}
    {% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" name="kword" id="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="50">ID</th>
                    <th width="100">NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="200">DEPARTAMENTO</th>
                    <th width="100">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                  {% for e in lista %}
                  <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            <!-- si existe paginacion => is_paginated, mostramos la barra de paginacion -->
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    <!-- Si tiene paginas atras-->
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                    </li>
                    {% endif %}

                    <!-- Mostrar Numero de paginas totales 1 2 3 4 5 6 7 -->
                    {% for pagina in paginator.page_range %}


                    {% if pagina == page_obj.number %}
                        <li class="current"><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                    {% else %}
                        <li ><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                    {% endif %}


                    {% endfor %}
                  
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>    
            {% endif %}
        </div>
    </div>

</div>

{% endblock content %}

empleado/templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block titulo %}
    Empleados por Departamento
{% endblock titulo %}

{% block content %}
    {% include 'includes/header.html' %}
<!--     <h1>Empleados por Departamento</h1> -->
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por area:</div>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="50">ID</th>
                            <th width="150">NOMBRES</th>
                            <th width="100">APELLIDOS</th>
                            <th width="100">DEPARTAMENTO</th>
                            <th width="100">ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                        <tr>
                            <td>{{ e.id }}</td>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento }}</td>
                            <td>
                                <a class="button alert" href="#">Eliminar </a>
                                <a class="button success" href="#">Editar </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>

    </div>

    {% for e in object_list %}
    <li>{{ e }}</li>
    {% endfor %}

{% endblock content %}
    

empleado/templates/persona/lista_empleados.html
{% extends 'base.html' %}


{% block titulo %}
    Empleados Admin
{% endblock titulo %}
    

{% block content %}
    {% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="30">ID</th>
                    <th width="100">NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="200">DEPARTAMENTO</th>
                    <th width="100">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                  {% for e in empleadoslista %}
                  <tr>
                    <td>{{ e.id }}</td>
                    <td>{{ e.first_name }}</td>
                    <td>{{ e.last_name }}</td>
                    <td>{{ e.departamento }}</td>
                    <td>
                        <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                        <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            <!-- si existe paginacion => is_paginated, mostramos la barra de paginacion -->
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    <!-- Si tiene paginas atras-->
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{ page_obj.previous_page_number }}">Atras</a>
                    </li>
                    {% endif %}

                    <!-- Mostrar Numero de paginas totales 1 2 3 4 5 6 7 -->
                    {% for pagina in paginator.page_range %}


                    {% if pagina == page_obj.number %}
                        <li class="current"><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                    {% else %}
                        <li ><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                    {% endif %}


                    {% endfor %}
                  
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>    
            {% endif %}
        </div>
    </div>

</div>

{% endblock content %}

empleado/templates/persona/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Procesamiento correcto</title>
</head>
<body>
    <h1>se procesó el formulario.</h1>
</body>
</html>

empleado/templates/persona/update.html
{% extends 'base.html' %}


{% block titulo %}
    Editar Empleado
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">MODIFICAR DATOS DEL EMPLEADO</h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Area:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades extra:
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Foto:
                        {{form.image}}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>

<!--                 <div class="cell large-12">
                    {{ form.as_p }}
                </div>-->

            </form>
        </div>
    </div>
</div>    
{% endblock content %}