empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'app_dpto'

urlpatterns = [
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name='nuevo_departamento'
    ),
    path(
        'departamento_lista',
        views.DepartamentoListView.as_view(),
        name='departamento_list'
    ),
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views
# usando reverse_lazy debemos especificar la etiqueta NAME de una URL

# Usando reverse_lazy definimos la variable para todo el conjunto de URL
# La convencion recomienda usar el nombre del modelo seguido de _app
app_name = "persona_app"
urlpatterns = [
     path(
          'lista-todo-empleados/', 
          views.ListAllEmpleados.as_view(),
          name='empleados_all'
     ),
     path(
          'lista-by-area/<corto>', 
          views.ListByAreaEmpleado.as_view(),
          name='empleados_area'
     ),
     path(
          'lista-empleados-admin',
          views.ListaEmpleadosAdmin.as_view(),
          name='empleados_admin'
     ),
     path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
     path('listar-habilidades/', views.ListHabilidadesEmpleado.as_view()),
     path('listar-por-trabajo/', views.ListEmpleadoByTrabajo.as_view()),
     path(
          'ver-empleado/<pk>/', 
          views.DetalleEmpleado.as_view(),
          name='empleado_detail'
     ),
     path(
          'add-empleado/',
          views.EmpleadoCreateView.as_view(),
          name='empleado_agrega'
     ),
     path(
          'success/', 
          views.SuccessView.as_view(), 
          name='correcto'
     ),
     path(
          'update-empleado/<pk>/',
          views.EmpleadoUpdateView.as_view(),
          name='modificar_empleado'
     ),
     path(
          'delete-empleado/<pk>/',
          views.EmpleadoDeleteView.as_view(),
          name='eliminar_empleado'
     ),
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from applications.home.views import IndexView
# Importar configuracion de django
from django.conf import settings
# importar paquete que ayuda a generar URLs estaticas
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('home/', IndexView.as_view()),
    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Ver archivos dentro de la carpeta MEDIA

empleado/applications/departamento/models.py
from django.db import models

# Create your models here.
# Modelo o Tabla de BD
class Departamento(models.Model):
    # ('Nombre') => nombre como se vera en el admin de django
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    # Personalizar aspecto del modelo en el admin de DJANGO
    class Meta:
        # Django agregara la S al final del nombre
        verbose_name = 'Oficinas de la empresa'
        # En plural
        verbose_name_plural = 'Areas de la empresa'
        # Ordenando los registros en base al campo
        ordering = ['-name']
        # No se registrara combinacion de campos iguales
        unique_together = ('name', 'shor_name')

    def __str__(self):
        #return str(self.id) + ' ' + self.name + ' - ' + self.shor_name
        return self.name + ' - ' + self.shor_name

empleado/applications/departamento/forms.py
# Para trabajar con formularios
from django import forms

# Formulario que NO depende de la tabla de BD
class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)
    

empleado/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView

# Importamos el FormView para trabajar con la vista generica simple
from django.views.generic.edit import FormView

# Importamos el modelo Empleado de otra aplicacion, haremos registro de datos
from applications.persona.models import Empleado

# Importamos el modelo Departamento, haremos registro de datos
from .models import Departamento

# Importamos el formulario que acabamos de crear
from .forms import NewDepartamentoForm

# Create your views here.


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = 'departamentos'

# Vista generica FormView, guarda dos modelos (tablas)
class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    # Hacemos referencia al formulario que creamos en forms.py
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('************** Estamos en el FORM VALID*************')

        # Procesando en modelo DEPARTAMENTO
        # Departamento pertenece a otro modelo, necesitamos 1 instancia de ese modelo
        # Variable depa utiliza la clase Departamento
        #con esto ya se creo una instancia para departamento
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            shor_name = form.cleaned_data['shorname']
        )
        # Con el metodo save() guardamos el valor en la BD
        depa.save()

        # Procesando en modelo EMPLEADO
        # Una forma de crear los registros es recuperar variables y asignarlo a cada campo 
        #Recuperamos datos que se envian por POST de Empleado desde forms.py
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']

        # Importamos del modelo Empleado de la otra aplicacion
        # Para crear un registro de la tabla empleado
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '3',
            departamento = depa,
            full_name = nombre + ' ' + apellido
        )
        return super(NewDepartamentoView, self).form_valid(form)

empleado/templates/departamento/lista.html
{% extends 'base.html' %}

{% block title %}
Lista Departamentos
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.shor_name }}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleados</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

empleado/templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block titulo %}
    Nuevo Departamento
{% endblock titulo %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Departamento - Nuevo</h1>
        <div class="cell">
            <form class="cell grid-x grid-margin-x" method="POST">{% csrf_token %}

                <div class="medium-12 cell">
                    <h3>Datos de Empleado</h3>
                </div>
                <div class="medium-6 cell">
                    <label>Nombre:
                        {{ form.nombre }}
                    </label>
                    <label>Apellidos:
                        {{ form.apellidos }}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <h3>Datos de Departamento</h3>
                </div>

                <div class="medium-6 cell">
                    <label>Departamento:
                        {{ form.departamento }}
                    </label>
                    <label>Nombre corto:
                        {{ form.shorname }}
                    </label>
                </div>

                <div class="medium-12 cell">
                    <button type="submit" class="button success">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}
    
    


</body>
</html>